### ISSUE TITLE
elm-review hook doesn't work in CI

### ISSUE THREAD

**Issue by catalogue-service** [gchq/nix-bootstrap#3]
The hook for elm-review doesn't work in CI as elm-json isn't available in the sandboxed environment mandated by `nix build .\#runChecks` doesn't contain it.

Find a way around this in a pure context.

**Comment by sd234678** [comment]
Closed in adf09ddb107b7019b9c9e5140d2bdb5f0f9a78d3 and b6fd8a5c285c78ad1fb3855d837ea491358f232e
